//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Vowpal Wabbit Common")]
[assembly: System.Reflection.AssemblyDescription("Vowpal Wabbit Common")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corp")]
[assembly: System.Reflection.AssemblyProduct("Vowpal Wabbit")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) Microsoft Corp 2012-2016, Yahoo! Inc. 2007-2012, and many individua" +
    "l contributors. All rights reserved")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("091c7906-1f69-44d5-a15f-fb29847a68ef")]
[assembly: System.Reflection.AssemblyVersion("8.3.0.9")]
[assembly: System.Reflection.AssemblyFileVersion("8.3.0.9")]


