{
  Checks: "-*,performance-unnecessary-copy-initialization,performance-for-range-copy,performance-move-const-arg,modernize-use-using",
  WarningsAsErrors: "-*,performance-unnecessary-copy-initialization,performance-for-range-copy,performance-move-const-arg,modernize-use-using",
  CheckOptions:
    [
      {
        key: performance-move-const-arg.CheckTriviallyCopyableMove,
        value: '0',
      }
    ]
}
