{
  Checks: "-*,performance-*",
  WarningsAsErrors: "-*,performance-*",
  CheckOptions:
    [
      {
        key: performance-move-const-arg.CheckTriviallyCopyableMove,
        value: '0',
      }
    ]
}
