//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Vowpal Wabbit Parallel")]
[assembly: System.Reflection.AssemblyDescription("Vowpal Wabbit Parallel")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corp")]
[assembly: System.Reflection.AssemblyProduct("Vowpal Wabbit")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) Microsoft Corp 2012-2016, Yahoo! Inc. 2007-2012, and many individua" +
    "l contributors. All rights reserved")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("0bb98c1a-b25f-43a0-94b6-fed77f7e5cd8")]
[assembly: System.Reflection.AssemblyVersion("8.3.0.9")]
[assembly: System.Reflection.AssemblyFileVersion("8.3.0.9")]


