/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vowpalwabbit_spark_VowpalWabbitNative */

#ifndef _Included_vowpalwabbit_spark_VowpalWabbitNative
#define _Included_vowpalwabbit_spark_VowpalWabbitNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vowpalwabbit_spark_VowpalWabbitNative
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vowpalwabbit_spark_VowpalWabbitNative_initialize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitNative
 * Method:    initializeFromModel
 * Signature: (Ljava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_vowpalwabbit_spark_VowpalWabbitNative_initializeFromModel
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitNative
 * Method:    getModel
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_vowpalwabbit_spark_VowpalWabbitNative_getModel
  (JNIEnv *, jobject);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitNative
 * Method:    getArguments
 * Signature: ()Lvowpalwabbit/spark/VowpalWabbitArguments;
 */
JNIEXPORT jobject JNICALL Java_vowpalwabbit_spark_VowpalWabbitNative_getArguments
  (JNIEnv *, jobject);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitNative
 * Method:    endPass
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_VowpalWabbitNative_endPass
  (JNIEnv *, jobject);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitNative
 * Method:    finish
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_VowpalWabbitNative_finish
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class vowpalwabbit_spark_VowpalWabbitExample */

#ifndef _Included_vowpalwabbit_spark_VowpalWabbitExample
#define _Included_vowpalwabbit_spark_VowpalWabbitExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vowpalwabbit_spark_VowpalWabbitExample
 * Method:    initialize
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_vowpalwabbit_spark_VowpalWabbitExample_initialize
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitExample
 * Method:    finish
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_vowpalwabbit_spark_VowpalWabbitExample_finish
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitExample
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_VowpalWabbitExample_clear
  (JNIEnv *, jobject);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitExample
 * Method:    addToNamespaceDense
 * Signature: (CI[D)V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_VowpalWabbitExample_addToNamespaceDense
  (JNIEnv *, jobject, jchar, jint, jdoubleArray);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitExample
 * Method:    addToNamespaceSparse
 * Signature: (C[I[D)V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_VowpalWabbitExample_addToNamespaceSparse
  (JNIEnv *, jobject, jchar, jintArray, jdoubleArray);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitExample
 * Method:    setLabel
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_VowpalWabbitExample_setLabel
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitExample
 * Method:    learn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_VowpalWabbitExample_learn
  (JNIEnv *, jobject);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitExample
 * Method:    predict
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_vowpalwabbit_spark_VowpalWabbitExample_predict
  (JNIEnv *, jobject);

/*
 * Class:     vowpalwabbit_spark_VowpalWabbitExample
 * Method:    getPrediction
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_vowpalwabbit_spark_VowpalWabbitExample_getPrediction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class vowpalwabbit_spark_ClusterSpanningTree */

#ifndef _Included_vowpalwabbit_spark_ClusterSpanningTree
#define _Included_vowpalwabbit_spark_ClusterSpanningTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vowpalwabbit_spark_ClusterSpanningTree
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vowpalwabbit_spark_ClusterSpanningTree_create
  (JNIEnv *, jclass);

/*
 * Class:     vowpalwabbit_spark_ClusterSpanningTree
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_ClusterSpanningTree_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vowpalwabbit_spark_ClusterSpanningTree
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_ClusterSpanningTree_start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vowpalwabbit_spark_ClusterSpanningTree
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vowpalwabbit_spark_ClusterSpanningTree_stop
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
