path_classifiers:
  library:
    - ext_libs
queries:
  exclude: "cs/useless-assignment-to-local"
extraction:
  java:
    after_prepare:
      - sed 's/@PACKAGE_VERSION@-SNAPSHOT/0-lgtmdummyver/g' $LGTM_SRC/java/pom.xml.in > $LGTM_SRC/java/pom.xml
  csharp:
    index:
      buildless: true
  cpp:
    prepare:
      packages:
        - zlib1g-dev
    configure:
      command:
        - cmake -S . -B build -DBUILD_FLATBUFFERS=Off -DBUILD_TESTING=Off -DRAPIDJSON_SYS_DEP=Off -DFMT_SYS_DEP=Off -DSPDLOG_SYS_DEP=Off -DVW_BOOST_MATH_SYS_DEP=Off -DVW_INSTALL=Off
