path_classifiers:
  library:
    - ext_libs
queries:
  exclude: "cs/useless-assignment-to-local"
extraction:
  java:
    after_prepare:
      - sed 's/@PACKAGE_VERSION@-SNAPSHOT/0-lgtmdummyver/g' $LGTM_SRC/java/pom.xml.in > $LGTM_SRC/java/pom.xml
  csharp:
    index:
      buildless: true
  cpp:
    configure:
      command:
        - .scripts/linux/install-flatbuffers.sh
