#!/bin/sh

# An example cluster command.  This just runs on one machine.
export FLAGS='-l 20 --power_t 0.5 --daemon --quiet --predictto localhost:39525'
./vw -l 20 --power_t 0.5 --multisource 2 --port 39525 --quiet &
./vw --port 39523 $FLAGS &
./vw --port 39524 $FLAGS &
sleep 1
./vw -d data --sendto localhost:39523 --sendto localhost:39524 
