codecov:
  token: dd972a6b-956e-4d07-acf4-2373926d8293

# Don't add the PR comment
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        base: auto
        # Coverage can drop by 0.5% before it is a failure.
        threshold: 0.5%
        after_n_builds: 0
        paths:
          - "vowpalwabbit/"

ignore:
  - "**/tests/"
  - "**/test/"
  - "test/"
  - "library/"
  - "utl/"
  - "ext_libs/"
