# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import vowpalwabbit

sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('../../'))



#   Interactive online version:
#   <span style="white-space: nowrap;"><a href="https://mybinder.org/v2/gh/spatialaudio/nbsphinx/{{ env.config.release|e }}?filepath={{ docname|e }}"><img alt="Binder badge" src="https://mybinder.org/badge_logo.svg" style="vertical-align:text-bottom"></a>.</span>
# nbsphinx_prolog = r"""
# {% set docname = 'doc/' + env.doc2path(env.docname, base=None) %}

# .. raw:: html

#     <div class="admonition note">
#       This page was generated from
#       <a class="reference external" href="https://github.com/VowpalWabbit/vowpalwabbit/blob/master/python/examples/{{ docname|basename|e }}">{{ docname|basename|e }}</a>.
#     </div>
# """

# -- Project information -----------------------------------------------------

project = u'VowpalWabbit'
copyright = u'2019, John langford et al'
author = u'John langford et al'


# Read version automatically from vowpalwabbit.__version__--------------------

version = vowpalwabbit.__version__

release = version

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.coverage',
    'numpydoc',
    'sphinx.ext.githubpages',
    'sphinx_thebe',
    "myst_nb",
]

jupyter_execute_notebooks = "cache"
thebe_config = {
    "repository_url": "https://github.com/jackgerrits/vowpal_wabbit",
    "repository_branch": "nbtest",
}
show_navbar_depth = 2

html_theme_options = {
    "path_to_docs": "python/docs/source",
    "repository_url": "https://github.com/jackgerrits/vowpal_wabbit",
    "repository_branch": "nbtest",
    "launch_buttons": {
        "binderhub_url": "https://mybinder.org",
        "notebook_interface": "jupyterlab",
        "thebe": True,
    },
    "use_repository_button": True,
    "use_edit_page_button": True,
    "home_page_in_toc": True,
    "use_issues_button": True,
    "use_download_button": False,
    "use_fullscreen_button": False,
}

# This helps to document __init__
def skip(app, what, name, obj, would_skip, options):
    if name == "__init__":
        return False
    return would_skip

def setup(app):
    app.connect("autodoc-skip-member", skip)

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_book_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']



html_sidebars = { '**': ['globaltoc.html', 'sourcelink.html', 'searchbox.html'] }


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}
# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}
