name: Bug Report
description: Report a bug in VW
labels: ["Bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: |
        - How did VW behave? Please include any stack trace, log messages or crash logs
        - What would you expect VW to do in this case?
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: How to reproduce
      description: "Steps to reproduce the bug. If possible, please verify with the latest released version to make sure it hasn't already been fixed."
      placeholder: |
        - Used this specific command line i.e. `vw -k -d train-sets/0001.dat --progress 10`
        - Used `model_file`
        - Used `specific_data_set`
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of VW did you use?
      placeholder: "9.0.1 or git commit: 19a64a47c"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: What OS did you use?
      placeholder: "Windows, macOS, Linux, etc."
    validations:
      required: true
  - type: input
    id: language
    attributes:
      label: Language
      description: What language/package did you use?
      placeholder: "Python, CLI, C++, C#, etc."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
