# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExampleCollection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsExampleCollection(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExampleCollection()
        x.Init(buf, n + offset)
        return x

    # ExampleCollection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExampleCollection
    def Examples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Example import Example
            obj = Example()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExampleCollection
    def ExamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExampleCollection
    def ExamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ExampleCollectionStart(builder): builder.StartObject(1)
def ExampleCollectionAddExamples(builder, examples): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(examples), 0)
def ExampleCollectionStartExamplesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ExampleCollectionEnd(builder): return builder.EndObject()
