# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Example(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsExample(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Example()
        x.Init(buf, n + offset)
        return x

    # Example
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Example
    def Namespaces(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Namespace import Namespace
            obj = Namespace()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Example
    def NamespacesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Example
    def NamespacesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Example
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Label import Label
            obj = Label()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ExampleStart(builder): builder.StartObject(2)
def ExampleAddNamespaces(builder, namespaces): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(namespaces), 0)
def ExampleStartNamespacesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ExampleAddLabel(builder, label): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)
def ExampleEnd(builder): return builder.EndObject()
