# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Label(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLabel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Label()
        x.Init(buf, n + offset)
        return x

    # Label
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Label
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Label
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def LabelStart(builder): builder.StartObject(2)
def LabelAddLabel(builder, label): builder.PrependFloat32Slot(0, label, 0.0)
def LabelAddWeight(builder, weight): builder.PrependFloat32Slot(1, weight, 0.0)
def LabelEnd(builder): return builder.EndObject()
