/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vowpalWabbit_learner_VWLearners_VWReturnType */

#ifndef _Included_vowpalWabbit_learner_VWLearners_VWReturnType
#define _Included_vowpalWabbit_learner_VWLearners_VWReturnType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
