/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vowpalWabbit_learner_VWMulticlassLearner */

#ifndef _Included_vowpalWabbit_learner_VWMulticlassLearner
#define _Included_vowpalWabbit_learner_VWMulticlassLearner
#ifdef __cplusplus
extern "C" 
{
#endif
/*
 * Class:     vowpalWabbit_learner_VWMulticlassLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)I
 */
JNIEXPORT jint JNICALL Java_vowpalWabbit_learner_VWMulticlassLearner_predict
  (JNIEnv *, jobject, jstring, jboolean, jlong);

/*
 * Class:     vowpalWabbit_learner_VWMulticlassLearner
 * Method:    predictMultiline
 * Signature: ([Ljava/lang/String;ZJ)I
 */
JNIEXPORT jint JNICALL Java_vowpalWabbit_learner_VWMulticlassLearner_predictMultiline
  (JNIEnv *, jobject, jobjectArray, jboolean, jlong);

/*
 * Class:     vowpalWabbit_learner_VWMulticlassLearner
 * Method:    predictForAllLines
 * Signature: ([Ljava/lang/String;ZJ)[I
 */
JNIEXPORT jintArray JNICALL Java_vowpalWabbit_learner_VWMulticlassLearner_predictForAllLines
  (JNIEnv *, jobject, jobjectArray, jboolean, jlong);

/*
 * Class:     vowpalWabbit_learner_VWMulticlassLearner
 * Method:    predictNamedLabelsForAllLines
 * Signature: ([Ljava/lang/String;ZJ)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_vowpalWabbit_learner_VWMulticlassLearner_predictNamedLabelsForAllLines
  (JNIEnv *, jobject, jobjectArray, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
