/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_learner_VWBase */

#ifndef _Included_vw_learner_VWBase
#define _Included_vw_learner_VWBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vw_learner_VWBase
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vw_learner_VWBase_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vw_learner_VWBase
 * Method:    closeInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vw_learner_VWBase_closeInstance
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
