/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_learner_VWFactory */

#ifndef _Included_vw_learner_VWFactory
#define _Included_vw_learner_VWFactory
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     vw_learner_VWFactory
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vw_learner_VWFactory_initialize
(JNIEnv *, jobject, jstring);

/*
 * Class:     vw_learner_VWFactory
 * Method:    getReturnType
 * Signature: (J)V
 */
JNIEXPORT jobject JNICALL Java_vw_learner_VWFactory_getReturnType
(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
