/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_learner_MultilabelsLearner */

#ifndef _Included_vw_learner_MultilabelsLearner
#define _Included_vw_learner_MultilabelsLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     vw_learner_MultilabelsLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)Lvw/response/Multilabels
 */
JNIEXPORT jobject JNICALL Java_vw_learner_MultilabelsLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

/*
 * Class:     vw_learner_MultilabelsLearner
 * Method:    predictMultiline
 * Signature: ([Ljava/lang/String;ZJ)Lvw/response/Multilabels
 */
JNIEXPORT jobject JNICALL Java_vw_learner_MultilabelsLearner_predictMultiline
(JNIEnv *, jobject, jobjectArray, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
