/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_learner_VWActionScoresLearner */

#ifndef _Included_vw_learner_VWActionScoresLearner
#define _Included_vw_learner_VWActionScoresLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     vw_learner_VWActionScoresLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)vw/response/ActionScores;
 */
JNIEXPORT jobject JNICALL Java_vw_learner_VWActionScoresLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

/*
 * Class:     vw_learner_VWActionScoresLearner
 * Method:    predictMultiline
 * Signature: ([Ljava/lang/String;ZJ)vw/response/ActionScores;
 */
JNIEXPORT jobject JNICALL Java_vw_learner_VWActionScoresLearner_predictMultiline
(JNIEnv *, jobject, jobjectArray, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
