/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_LDA */

#ifndef _Included_vw_LDA
#define _Included_vw_LDA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vw_LDA
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_vw_LDA_predict
  (JNIEnv *, jobject, jstring, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
