/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_learner_VWIntArrayLearner */

#ifndef _Included_vw_learner_VWIntArrayLearner
#define _Included_vw_learner_VWIntArrayLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     vw_learner_VWIntArrayLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)[F
 */
JNIEXPORT jintArray JNICALL Java_vw_learner_VWIntArrayLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong, jlong);

/*
 * Class:     vw_learner_VWIntArrayLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)[F
 */
JNIEXPORT jintArray JNICALL Java_vw_learner_VWIntArrayLearner_predictMultiline
(JNIEnv *, jobject, jobjectArray, jboolean, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
