/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_learner_ScalarLearner */

#ifndef _Included_vw_learner_ScalarLearner
#define _Included_vw_learner_ScalarLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     vw_learner_ScalarLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)F
 */
JNIEXPORT jfloat JNICALL Java_vw_learner_ScalarLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

/*
 * Class:     vw_learner_ScalarLearner
 * Method:    predictMultiline
 * Signature: ([Ljava/lang/String;ZJ)F
 */
JNIEXPORT jfloat JNICALL Java_vw_learner_ScalarLearner_predictMultiline
(JNIEnv *, jobject, jobjectArray, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
