/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_learner_MulticlassLearner */

#ifndef _Included_vw_learner_MulticlassLearner
#define _Included_vw_learner_MulticlassLearner
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     vw_learner_MulticlassLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)I
 */
JNIEXPORT jint JNICALL Java_vw_learner_MulticlassLearner_predict
(JNIEnv *, jobject, jstring, jboolean, jlong);

/*
 * Class:     vw_learner_MulticlassLearner
 * Method:    predictMultiline
 * Signature: ([Ljava/lang/String;ZJ)I
 */
JNIEXPORT jint JNICALL Java_vw_learner_MulticlassLearner_predictMultiline
(JNIEnv *, jobject, jobjectArray, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
