/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_learner_VWTopicLearner */

#ifndef _Included_vw_learner_VWTopicLearner
#define _Included_vw_learner_VWTopicLearner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vw_learner_VWTopicLearner
 * Method:    predict
 * Signature: (Ljava/lang/String;ZJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_vw_learner_VWTopicLearner_predict
  (JNIEnv *, jobject, jstring, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
