/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_VW */

#ifndef _Included_vw_VW
#define _Included_vw_VW
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     vw_VW
   * Method:    version
   * Signature: ()Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL Java_vw_VW_version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
