/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_VWScalarPredictor */

#ifndef _Included_vw_VWScalarPredictor
#define _Included_vw_VWScalarPredictor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vw_VWScalarPredictor
 * Method:    predictFloat
 * Signature: (Ljava/lang/String;ZJ)F
 */
JNIEXPORT jfloat JNICALL Java_vw_VWScalarPredictor_predictFloat
  (JNIEnv *, jobject, jstring, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
