/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_VowpalWabbit */

#ifndef _Included_vw_VowpalWabbit
#define _Included_vw_VowpalWabbit
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     vw_VowpalWabbit
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vw_VowpalWabbit_version
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
