/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vw_VWScorer */

#ifndef _Included_vw_VWScorer
#define _Included_vw_VWScorer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vw_VWScorer
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vw_VWScorer_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vw_VWScorer
 * Method:    getPrediction
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_vw_VWScorer_getPrediction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vw_VWScorer
 * Method:    closeInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vw_VWScorer_closeInstance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
