#!/bin/bash
set -e
set -x

if [ "$#" -ne 1 ]; then
    echo "Must supply version number: $0 new_version_number"
    exit 1
fi

# Clean working directory
git clean -fd .
git checkout -- .

# Run clang-format and commit
./utl/clang-format fix
git commit -a -m "Fix style with clang-format (before releasing $1)"

# Update version number and commit
echo "$1" > version.txt
git commit -a -m "Update verson.txt for release $1"

# Tag release commit and push
git tag $1
git push origin $1
