trigger:
  - master
  - releases/**

pr:
  - master
  - releases/**

pool:
  vmImage: 'ubuntu-latest'

container:
  image: vowpalwabbit/ubuntu2004-build:latest
  endpoint: DockerHub

steps:
- bash: ./.scripts/linux/build-static-java.sh
  displayName: Build C++
- bash: ./.scripts/linux/java.sh
  displayName: Build + test Java
  env:
    # these are credentials used to publish to oss.sonatype.org
    # credentials are stored as secrets in the build definition
    ossrh_gpg: $(ossrh_gpg)
    ossrh_username: $(ossrh_username)
    ossrh_password: $(ossrh_password)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: build/java/libvw_jni.so
    artifactName: 'vw-static-linux-64'
  displayName: 'java artifact linux 64'
