trigger:
- master
- 'releases/**'

pr:
- '*'

pool:
  vmImage: 'macOS-10.14'

steps:
- bash: .scripts/macos/restore.sh $(Build.SourcesDirectory)
  displayName: 'Restore dependencies'
- bash: .scripts/macos/build.sh $(Build.SourcesDirectory)
  displayName: 'Build'
- bash: .scripts/macos/test.sh $(Build.SourcesDirectory)
  displayName: 'Run tests'
