name: Windows / Python

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        config:
        - { version: 3.6, vcpkg_commit: e2049cb9754006b6a2abed781d34030e16702fad}
        - { version: 3.7, vcpkg_commit: e2049cb9754006b6a2abed781d34030e16702fad}
        - { version: 3.8, vcpkg_commit: e2049cb9754006b6a2abed781d34030e16702fad}
        - { version: 3.9, vcpkg_commit: fe112d8301e13fde9a25dc92d94a0c4a6dc3cf19}
        - { version: "3.10", vcpkg_commit: 761c81d43335a5d5ccc2ec8ad90bd7e2cbba734e}
    steps:
      - name: Set up Python ${{ matrix.config.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.version }}
      - uses: actions/checkout@v2
        with:
          repository: microsoft/vcpkg
          ref: ${{ matrix.config.vcpkg_commit }}
          path: ${{github.workspace}}\\vcpkg
      - name: Cache vcpkg
        id: vcpkg-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}\\vcpkg
          key: ${{ runner.os }}-${{ matrix.config.version }}-${{ matrix.config.vcpkg_commit }}-2
      # Downgrade CMake to mitigate crashing issue introduced in 3.21 that only affects vcpkg. See here: https://github.com/microsoft/vcpkg/issues/18718
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.20.x'
      - name: Bootstrap and install vcpkg packages
        shell: powershell
        if: steps.vcpkg-cache.outputs.cache-hit != 'true'
        run: |
          cd ${{github.workspace}}\\vcpkg
          .\\bootstrap-vcpkg.bat
          .\\vcpkg.exe --triplet x64-windows install zlib boost-program-options boost-align boost-foreach boost-python boost-math python3 flatbuffers
      - uses: actions/checkout@v2
        with:
          path: ${{github.workspace}}\\vowpal_wabbit
      - name: Build wheel
        shell: powershell
        run: |
          cd ${{github.workspace}}\\vowpal_wabbit
          pip install wheel
          pip wheel . -w ${{github.workspace}}\\wheel_output --global-option --vcpkg-root="${{github.workspace}}\\vcpkg" --verbose
      - name: Upload built wheel
        uses: actions/upload-artifact@v1
        with:
          name: wheel_${{ matrix.config.version }}
          path: wheel_output
  test:
    needs: build
    runs-on: windows-2019
    strategy:
      matrix:
        config:
        - { version: 3.6 }
        - { version: 3.7 }
        - { version: 3.8 }
        - { version: 3.9 }
        - { version: "3.10" }
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.config.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.version }}
      - name: Download wheel
        uses: actions/download-artifact@v1
        with:
          name: wheel_${{ matrix.config.version }}
      - name: Install deps and test wheel
        shell: bash
        run: |
          export wheel_files=(wheel_${{ matrix.config.version }}/*)
          export wheel_file="${wheel_files[0]}"
          echo Installing ${wheel_file}...
          pip install -r requirements.txt
          pip install pytest
          pip install ${wheel_file}
          python -m pytest .\\python\\tests\\
          python .\\python\\tests\\run_doctest.py
