name: Windows / Python

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        config:
        # - { version: "3.6", vcpkg_manifest: "python\\vcpkg_default.json", overlay_ports: "python\\vcpkg_python_override_ports\\python36\\"}
        - { version: "3.7", vcpkg_manifest: "python\\vcpkg_default.json", overlay_ports: "python\\vcpkg_python_override_ports\\python37\\"}
        - { version: "3.8", vcpkg_manifest: "python\\vcpkg_default.json", overlay_ports: "python\\vcpkg_python_override_ports\\python38\\" }
        # - { version: "3.9", vcpkg_manifest: "python\\vcpkg_python39.json", overlay_ports: "" }
        # - { version: "3.10", vcpkg_manifest: "python\\vcpkg_python310.json", overlay_ports: "" }
    steps:
      - name: Set up Python ${{ matrix.config.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.version }}
      - uses: actions/checkout@v2
        with:
          repository: microsoft/vcpkg
          ref: a515872b1abf58b639bf8b15ab5fe23b62f25ac3
          fetch-depth: 0
          path: ${{github.workspace}}\\vcpkg
      - name: Cache vcpkg
        id: vcpkg-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}\\vcpkg
          key: ${{ runner.os }}-${{ matrix.config.version }}-a515872b1abf58b639bf8b15ab5fe23b62f25ac3-2
      # Downgrade CMake to mitigate crashing issue introduced in 3.21 that only affects vcpkg. See here: https://github.com/microsoft/vcpkg/issues/18718
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.20.x'
      - uses: actions/checkout@v2
        with:
          path: ${{github.workspace}}\\vowpal_wabbit
      - name: Build wheel
        shell: powershell
        run: |
          cd ${{github.workspace}}\\vowpal_wabbit
          cp ${{ matrix.config.vcpkg_manifest }} vcpkg.json
          pip install wheel
          pip wheel . -w ${{github.workspace}}\\wheel_output --global-option --vcpkg-root="${{github.workspace}}\\vcpkg" --global-option --cmake-generator="Visual Studio 16 2019" --global-option --cmake-options="-DVCPKG_OVERLAY_PORTS=${{github.workspace}}\\vowpal_wabbit\\${{ matrix.config.overlay_ports }}"  --verbose
      - name: Upload built wheel
        uses: actions/upload-artifact@v1
        # with:
        #   name: wheel_${{ matrix.config.version }}
        #   path: wheel_output
        if: always()
        with:
          name: logs
          path: ${{github.workspace}}\\vcpkg\\buildtrees\\python3\\build-x64-windows-rel-out.log
  # test:
  #   needs: build
  #   runs-on: windows-2019
  #   strategy:
  #     matrix:
  #       config:
  #       # - { version: "3.6" }
  #       # - { version: "3.7" }
  #       # - { version: "3.8" }
  #       # - { version: "3.9" }
  #       # - { version: "3.10" }
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python ${{ matrix.config.version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.config.version }}
  #     - name: Download wheel
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: wheel_${{ matrix.config.version }}
  #     - name: Install deps and test wheel
  #       shell: bash
  #       run: |
  #         export wheel_files=(wheel_${{ matrix.config.version }}/*)
  #         export wheel_file="${wheel_files[0]}"
  #         echo Installing ${wheel_file}...
  #         pip install -r requirements.txt
  #         pip install pytest
  #         pip install ${wheel_file}
  #         python -m pytest .\\python\\tests\\
  #         python .\\python\\tests\\run_doctest.py
