name: Windows / C++ - Sln

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

jobs:
  check:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: darenm/Setup-VSTest@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - run: Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList 'modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --quiet --add Microsoft.Net.ComponentGroup.4.6.2.DeveloperTools' -Wait -PassThru
      - run: Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList 'modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --quiet --add Microsoft.VisualStudio.Component.VC.v141.CLI.Support' -Wait -PassThru
      - run: CALL .scripts/restore.cmd
        name: 'Restore dependencies'
        shell: cmd
        env:
          nugetPath: ${{ github.workspace }}\vowpalwabbit\.nuget\nuget.exe
      - run: CALL .scripts/build.cmd
        name: 'Build vw.sln'
        shell: cmd
        env:
          nugetPath: ${{ github.workspace }}\vowpalwabbit\.nuget\nuget.exe
      - run: CALL .scripts/test.cmd
        name: 'Run tests'
        shell: cmd
        env:
          nugetPath: ${{ github.workspace }}\vowpalwabbit\.nuget\nuget.exe
      - run: CALL .scripts/package.cmd
        name: 'Package artifacts'
        shell: cmd
        env:
          nugetPath: ${{ github.workspace }}\vowpalwabbit\.nuget\nuget.exe
          Tag: -${{github.sha}}--unknown
          SourceInfo: 'Built from commit id: ${{github.sha}}'
