name: Python lint

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

jobs:
  typecheck:
    container:
      image: vowpalwabbit/manylinux2010-build:latest
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.config.experimental }}
    strategy:
      matrix:
        config:
        - { version: 3.8, base_path: /opt/python/cp38-cp38/, include_dir_name: python3.8/, experimental: false }
    steps:
      # v1 must be used because newer versions require a node.js version that will not run on this old image.
      - uses: actions/checkout@v1
      - name: add to path
        shell: bash
        run: |
          echo "${{ matrix.config.base_path }}bin" >> $GITHUB_PATH
      - name: Build + check
        shell: bash
        run: |
          ${{ matrix.config.base_path }}bin/python setup.py --cmake-options="-DSTATIC_LINK_VW_JAVA=On;-DPython_INCLUDE_DIR='${{ matrix.config.base_path }}include/${{ matrix.config.include_dir_name }}'" install
          ${{ matrix.config.base_path }}bin/pip install -r requirements.txt
          ${{ matrix.config.base_path }}bin/pip install pytype
          ${{ matrix.config.base_path }}bin/python -m pytype ./python/vowpalwabbit/ --verbosity=2
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: pip install black
      - run: python -m black --check python/vowpalwabbit
      - name: Formatting issue
        if: ${{ failure() }}
        run: echo "::error Formatting issues. To fix, run `python -m black python/vowpalwabbit`"
