name: Clang-tidy

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

jobs:
  run-clang-tidy:
    container:
      image: vowpalwabbit/ubuntu2004-dev:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure CMake
        shell: bash
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=On
      - name: Run clang tidy
        shell: bash
        run: ./.scripts/linux/run-clang-tidy.sh